name: "Deploy code With All Dependencies and Test Cases"
on: [push,workflow_dispatch]
jobs:
  DeployCode:
    runs-on: ubuntu-latest
    steps:
      - name: "Dispatch the code and Clone..."
        uses:  actions/checkout@v4
      - name: "Install NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "Check Node Version"
        run: node -v
      - name: "Install All App Dependencies"
        run: npm ci
      - name: "Run Test Cases"
        run: npm run test




