name: "Final Setup"
on: [push,workflow_dispatch]
jobs:
  finalCheck:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code and Clone..."
        uses: actions/checkout@v4
      - name: "Install Node Js In Runner"
        uses: actions/setup-node@v4
      - name: "Check Node Version"
        run: node -v
      - name: "install Application Dependencies"
        run: npm ci
      - name: "Run Test Cases"
        run: npm run test