name: "Creating My Own Yaml"
on: [push,workflow_dispatch]
jobs:
  clonecode:
    runs-on: ubuntu-latest
    steps:
      - name: "cloning the codebase"
        run: |
          echo "Cloning the codebase..."
          echo "${{toJSON(github)}}"
          git clone https://github.com/${{github.repository}}.git