name: "Next Day Check"
on: [push,workflow_dispatch]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: "Test Cases Running -- ${{runner.os}}"
        uses: actions/checkout@v4
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "Checking Node Version"
        run: node -v
      - name: "Install Application Dependencies"
        run: npm ci
      - name: "Code Test Cases Running"
        run: npm run test
  deployCode:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: "Test Cases Running"
        uses: actions/checkout@v4
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "Install Application Dependencies"
        run: npm ci
      - name: "Deployed Status"
        run: echo "Code Deployed Success."